version: '3.8'

services:
  nodejs:
    build: .
    image: nodejs_app 
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build: Dockerfile_nginx/
    image: nginx
    ports:
        - "80:80"